<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block
 */
$_order = $block->getOrder() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <?php $i = 0;
                $columns = $block->getColumns();
                $lastItemNumber = count($columns) ?>
                <th class="col-select-item"><span><?= /* @noEscape */ __('Select') ?></span></th>
                <?php foreach ($columns as $columnName => $columnTitle):?>
                    <?php $i++; ?>
                    <th class="col-<?= /* @noEscape */ $columnName ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= /* @noEscape */ $columnTitle ?></span></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            }?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                <?= $block->getItemHtml($_item) ?>
                <?= $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
<div class="select-item-popup" style="float: right;">
    <button class="select-item-popup-button primary" id="select-item-popup-button">
        <?= __('Send Supplier an Email') ?>
    </button>
</div>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<div class="popup-start-here" id="popup-modal" style="display: none;">
    <h2>
        <?= __('OnlyPOS - A brand of Swift Computers Pty Ltd. - Order # ').$_order->getIncrementId() ?>
    </h2>
    <div class="admin-content">
        <div class="supplier">
            <label for="supplier"><?= __('Supplier Name:') ?></label>
            <div class="content">
                <select name="supplier-name" id="supplier-name" class="supplier-name">
                    <?php
                    $supplyName = '';
                    foreach($_order->getAllItems() as $orItem) {
                        $productId = $orItem->getProductId();
                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
                        if($supplyName != $product->getAttributeText('supply_by'))
                        {
                            $supplyName = $product->getAttributeText('supply_by'); ?>
                            <option value="<?= $supplyName ?>"><?= $supplyName ?></option><?php
                        }
                    } ?>
                </select>
            </div>
        </div>
        <div class="supplier">
            <label for="supplier-email"><?= __('Supplier Email*:') ?></label>
            <div class="content">
                <input type="email" name="supplier-email" id="supplier-email" />
            </div>
        </div>
        <div class="supplier">
            <label for="supplier-cc"><?= __('Cc*:') ?></label>
            <div class="content">
                <input type="text" name="supplier-cc" id="supplier-cc" />
                <p><?= __('[use "," to separate e-mails.') ?></p>
            </div>
        </div>
        <div class="supplier">
            <label for="supplier-comments"><?= __('Comments (if any):') ?></label>
            <div class="content">
                <textarea name="supplier-comments" id="supplier-comments"></textarea>
                <p style="font-size:.7em;">Note: For new line use <<strong>br</strong>/> or <<strong>p</strong>> tag</p>
            </div>
        </div>
        <div class="supplier">
            <label for="supplier-message"><?= __('Message:') ?></label>
            <div class="content pro-name">
            </div>
        </div>
        <div class="supplier">
            <label for="supplier-signature"><?= __('Signature:') ?></label>
            <div class="content">
                <textarea name="signature" id="supplier-signature"></textarea>
                <p style="font-size:.7em;">Note: For new line use <<strong>br</strong>/> or <<strong>p</strong>> tag</p>
            </div>
        </div>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                // title: 'OnlyPOS - A brand of Swift Computers Pty Ltd.',
                buttons: [{
                    text: $.mage.__('Send Email'),
                    class: '',
                    click: function () {
                        // var itemId = $('.select-item-order:checked').val();
                        var name = jQuery('#supplier-name option:selected').text();
                        var orderId = "<?php echo $_order->getId() ?>";
                        var email = jQuery("#supplier-email").val();
                        var cc = jQuery("#supplier-cc").val();
                        var comments = jQuery("#supplier-comments").val();
                        var signature = jQuery("#supplier-signature").val();
                        var selected = new Array();
                        $("input:checkbox[name=selectcol]:checked").each(function() {
                           selected.push($(this).val());
                        });
                        // var filter = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;
                        if(email == '' || cc == '' || comments == '')
                        {
                            if(email == '')
                            {
                              jQuery('#supplier-email').focus();
                              jQuery('#supplier-email').css('border', '1px solid #ff0000');
                            }
                            if(cc == '')
                            {
                              jQuery('#supplier-cc').focus();
                              jQuery('#supplier-cc').css('border', '1px solid #ff0000');
                            }
                            if(comments == '')
                            {
                              jQuery('#supplier-comments').focus();
                              jQuery('#supplier-comments').css('border', '1px solid #ff0000');
                            }
                        }else{
                            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                            if (regex.test(email))
                            {
                                jQuery.ajax({
                                    url: "<?php  echo $block->getBaseUrl() . 'swiftposadmin/adminshipping/send/email';?>",
                                    type: 'POST',
                                    showLoader: true,
                                    data : {name:name, email:email, cc:cc, comments:comments, signature:signature, orderId:orderId, itemId:selected},
                                    success: function(data){
                                        window.scrollTo(0, 0);
                                        location.reload(true);
                                    },
                                    error: function(result){
                                        console.log('no response !');
                                    }
                                });
                                this.closeModal(); 
                            }else{
                                jQuery('#supplier-email').focus();
                                jQuery('#supplier-email').css('border', '1px solid #ff0000');
                            }                          
                        }
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#select-item-popup-button").on('click',function(){ 
                if($(".select-item-order").is(':checked'))
                {
                    var newselected = new Array();
                    $("input:checkbox[name=selectcol]:checked").each(function() {
                        newselected.push($(this).val());
                    });
                    var orderId = "<?php echo $_order->getId() ?>";
                    jQuery.ajax({
                        url: "<?php  echo $block->getBaseUrl() . 'swiftposadmin/adminshipping/send/productname';?>",
                        type: 'POST',
                        showLoader: true,
                        data : {orderId:orderId, itemId:newselected},
                        success: function(data){
                            $('.pro-name').html(data);
                            $("#popup-modal").modal("openModal");
                        }
                    });
                }else{
                    alert('Please Select Item first');
                }
                
            });
        }
    );
</script>
<style type="text/css">
    .sales-order-view .modal-inner-wrap {
        max-width: 50%;
    }
    .sales-order-view .admin-content .supplier {
        padding: 1em 1em 1em 0;
        clear: both;
    }
    .sales-order-view .admin-content .supplier label {
        font-weight: 600;
        width: 20%;
    }
    .sales-order-view .admin-content .supplier .content {
        display: inline-block;
        float: right;
        width: 72%;
    }
    .sales-order-view .admin-content .supplier .content textarea, .sales-order-view .admin-content .supplier .content input, .sales-order-view .admin-content .supplier .content select {
        border: 1px solid;
        width: 50%;
        max-width: 100%;
    }
    .sales-order-view .modal-footer button {
        background-color: #eb5202;
        border-color: #eb5202;
        color: #ffffff;
        text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.25);
        float: left;
    }
    .sales-order-view .admin-content .supplier .content p {
        display: inline-block;
        font-weight: 600;
    }
</style>