<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<div class="footer-container">
    <div class="footer">
        <?php echo $block->getChildHtml() ?>
		<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
	if ($request->getFullActionName() == 'cms_index_index') 
	{
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
	$routeName      = $requestInterface->getRouteName();
	$moduleName     = $requestInterface->getModuleName();
	$controllerName = $requestInterface->getControllerName();
	$actionName     = $requestInterface->getActionName();
	if($moduleName == 'cms' && $controllerName == "index" && $actionName == 'index') {
		//echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-home-page-content')->toHtml();
	}
	
}
?>
        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
    </div>
</div>
