<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
/** @var \Plumrocket\Amp\Helper\Homepage $homepageHelper */
$homepageHelper = $this->helper(\Plumrocket\Amp\Helper\Homepage::class);
$categories = $homepageHelper->getTopLevelCategories();
$mediaUrl = $homepageHelper->getMediaUrl() . 'catalog/category/';
$defaultImage = $this->getViewFileUrl('Plumrocket_Amp::images/photos/homepage-default.png');
$imageWidth = 210;
$imageHeight = 140;
?>

<!--amp-carousel id="custom-button" width="400" height="300" layout="responsive" type="slides" autoplay delay="2000">
  <amp-img src="https://www.onlypos.com.au/media/AMP/08-Zebra-Barcode-scanner.jpg" width="400" height="300" layout="responsive" alt="a sample image"></amp-img>
  <amp-img src="https://www.onlypos.com.au/media/AMP/06-SmartSled.jpg" width="400" height="300" layout="responsive" alt="another sample image"></amp-img>
  <amp-img src="https://www.onlypos.com.au/media/AMP/11-Star-Bluetooth-Printer.jpg" width="400" height="300" layout="responsive" alt="and another sample image"></amp-img>
</amp-carousel-->
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollectionFactory = $_objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$imageHelper  = $_objectManager->get('\Magento\Catalog\Helper\Image');
$priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data');
$collection = $productCollectionFactory->create();
$collection->addAttributeToSelect('*');
$collection->addAttributeToSort('entity_id','desc');
$collection->setOrder('updated_at', 'desc');
$collection->setPageSize(10); // selecting only 10 products
$imageheight=165;
$imagewidth=165;
?>
<?php 
$banner_collection = $_objectManager->create('FME\Banners\Model\ResourceModel\Banners\CollectionFactory')->create(); 
$banner_collection->addFieldToSelect('*');
$banner_collection->addFieldToFilter('status', 1);
$media_dir=$_objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<amp-carousel controls id="custom-button" width="400" height="300" layout="responsive" type="slides" autoplay delay="2000">
	<?php foreach ($banner_collection as $index => $banner) { ?>
	  <amp-img src="<?php echo $media_dir.$banner->getBannerimage()?>" width="400" height="300" layout="responsive" alt="a sample image"></amp-img>
	<?php }?>
</amp-carousel>



<div class="offer-banner"> 
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('amp-offer-banner')->toHtml();?>
<div>
<div class="latest-label"> 
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('label-latest')->toHtml();?>
<div>
<div class="carousel-parent">
	<amp-carousel controls class="carousel-component" height="300" width="<?php echo 2*$imagewidth;  ?>" layout="fixed-height" type="carousel">
	<?php
	 foreach ($collection as $product) { ?>
	<div class="slide">
		 <a href="<?php echo $product->getProductUrl()?>">
		 <amp-img src="<?php  echo $imageHelper->init($product, 'product_thumbnail_image')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();?>" width="<?php echo $imagewidth; ?>" height="<?php echo $imageheight; ?>" alt="<?php echo $product->getName(); ?>"></amp-img>
		 </a>
		<div class="amp-name-caption" >
			<?php echo substr($product->getName(),0,15)."..."?>
		</div>	
	<?php if(!$product->getSpecialPrice()){	?>	
		<div class="amp-price-caption">
			<?php echo $priceHelper->currency($product->getPrice(), true, false)?>
		</div>
	<?php }else{?>	
		<div class="amp-spcl-caption">
			<?php echo $priceHelper->currency($product->getSpecialPrice(), true, false)?>
		</div>
	<?php }?>	
    </div>
	 <?php 
		}
	?>
	</amp-carousel>
</div>
<div class="label-special"> 
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('label-special')->toHtml();?>
<div>

<div class="carousel-parent">
	<amp-carousel controls class="carousel-component" height="300" width="<?php echo 2*$imagewidth;  ?>" layout="fixed-height" type="carousel">
	<?php
	 foreach ($collection as $product) { ?>
	<div class="slide">
		 <a href="<?php echo $product->getProductUrl()?>">
		 <amp-img src="<?php  echo $imageHelper->init($product, 'product_thumbnail_image')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();?>" width="<?php echo $imagewidth; ?>" height="<?php echo $imageheight; ?>" alt="<?php echo $product->getName(); ?>"></amp-img>
		 </a>
		<div class="amp-name-caption" >
			<?php echo substr($product->getName(),0,15)."..."?>
		</div>	
	<?php if(!$product->getSpecialPrice()){	?>	
		<div class="amp-price-caption">
			<?php echo $priceHelper->currency($product->getPrice(), true, false)?>
		</div>
	<?php }else{?>	
		<div class="amp-spcl-caption">
			<?php echo $priceHelper->currency($product->getSpecialPrice(), true, false)?>
		</div>
	<?php }?>	
    </div>
	 <?php 
		}
	?>
	</amp-carousel>
</div>
<div class="label-special"> 
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('amp-top-category')->toHtml();?>
<div>

<!--div class="col-main">
    <div class="std">
        <div class="amp-cat">
            <?php //foreach ($categories as $category) : ?>
                <a href="<?php //$category->getUrl(); ?>">
                    <span>
                        <amp-img layout="responsive"
                                 src="<?php //$homepageHelper->getResizedImage($category, $imageWidth * 2, $imageHeight * 2, $defaultImage); ?>"
                                 alt="<?php // __('Category %s image', $category->getName())?>"
                                 height="<?php // $imageHeight; ?>"
                                 width="<?php // $imageWidth; ?>"></amp-img>
                        <span><?php //$category->getName() ?></span>
                    </span>
                </a>
            <?php //endforeach; ?>
        </div>
    </div>
</div-->

<div class="carousel-parent">
	<amp-carousel controls class="carousel-component" height="300" width="<?php echo 2*$imagewidth;  ?>" layout="fixed-height" type="carousel">
	<?php
	 foreach ($categories as $category) { ?>
	<div class="slide">
		 <a href="<?php echo $category->getUrl(); ?>">
		 <amp-img src="<?php  echo $homepageHelper->getResizedImage($category, $imageWidth, $imageHeight, $defaultImage); ?>" width="<?php echo $imagewidth; ?>" height="<?php echo $imageheight; ?>" alt="<?php  __('Category %s image', $category->getName())?>"></amp-img>
		 </a>
		<div class="amp-name-caption" >
			<?php echo $category->getName(); ?>
		</div>	
    </div>
	 <?php 
		}
	?>
	</amp-carousel>
</div>

 

<amp-carousel class="carousel2" controls layout="responsive" height="400" width="500" type="slides">
  <div class="slide">
    <amp-img src="https://www.onlypos.com.au/media/AMP/08-Zebra-Barcode-scanner.jpg" layout="fill"  alt="Border Collie"></amp-img>
    <div class="caption">
      The Border Collie is a working and herding dog breed developed in the Anglo-Scottish border region
      for herding livestock, especially sheep. It was specifically bred for intelligence and obedience.
    </div>
  </div>

  <div class="slide">
    <amp-img src="https://www.onlypos.com.au/media/AMP/06-SmartSled.jpg" layout="fill" alt="Shetland Sheepdog"></amp-img>
    <div class="caption">
      The Shetland Sheepdog, often known as the Sheltie, is a breed of herding dog. Less favored nicknames
      are the Toy Collie and the Miniature Collie. They are small dogs, and come in a variety of colors,
      such as sable, tri-color, and blue merle. They are very intelligent, vocal, excitable, energetic dogs
      who are always willing to please and work hard.
    </div>
  </div>
  
  <div class="slide">
    <amp-img src="https://www.onlypos.com.au/media/AMP/11-Star-Bluetooth-Printer.jpg" layout="fill" alt="Hovawart"></amp-img>
    <div class="caption">
      The Hovawart is a medium to large size German dog breed. The name of the breed means "an estate guard
      dog", which is the original use for the breed. The breed originated in the Black Forest region and was
      first described in text and paintings in medieval times.
    </div>
  </div>
</amp-carousel> 