<h4>Our Delivery Time is 1-2 Days* Normally!</h4>

<p>Products are shipped via well-known carriers of Australia viz., Star Track, Couriers Please, Toll Ipec etc. *Delivery depends on the location and may take longer if customers are located in the rural/remote area. Our couriers provide speedy shipping across Australia which includes Tasmania & Norfolk Island which could take an additional day.
    <a href="<?php echo $this->getUrl('delivery')?>" target="_blank">Read More about Delivery</a>.</p>
    