<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $request = $objectManager->get('\Magento\Framework\App\Request\Http');
    $moduleName = $request->getModuleName();
    $contollerName = $request->getControllerName();
    $actionName = $request->getActionName();
    $imageUrl = '';
   if($moduleName == 'catalog' && $contollerName == 'product' && $actionName == 'view') {
       $registry = $objectManager->get('\Magento\Framework\Registry');
       $currentProduct = $registry->registry('current_product');
       $brandAttrVale = $currentProduct->getManufacturer();
       $brandsObj = $objectManager->create('\Megnor\ShopByBrand\Model\Items')->getCollection();
       $brandsObj->addFieldToFilter('attribute_id', $brandAttrVale);
       $brandData = $brandsObj->getFirstItem()->getData();
	   if(isset($brandData['logo']))
         $imageUrl = $block->getUrl('pub/media/') . $brandData['logo'];
   }
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
    </h1>
    <?= $block->getChildHtml() ?>
    <?php if($imageUrl != ''){?>
        <img src="<?php echo $imageUrl ?>" style="height: 55px">
    <?php } ?>
</div>
<?php endif; ?>



