<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?= /* @escapeNotVerified */ $_code ?>">
        <td style="text-align:right;" colspan="2" <?php /* @escapeNotVerified $block->getLabelProperties() */ ?> scope="row">
            <?php if ($_total->getStrong() || $_total->getLabel() == "Grand Total"):?>
            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
            <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </td>
		<td></td>
        <td style="text-align:right;padding-right:9px;"  <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @escapeNotVerified */ str_replace(array("A","U"),array("",""),$block->formatValue($_total)) ?></strong>
            <?php else:?>
            <?= /* @escapeNotVerified */ str_replace(array("A","U"),array("",""),$block->formatValue($_total)) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
